name: very_good_coffee_app
description: "A Flutter app for discovering and saving coffee images"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  injectable: ^2.6.0
  go_router: ^14.2.7
  equatable: ^2.0.5
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

